#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 15:51:39 EEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=FreeVibrant v0.0.1.zip
enableShaders=false
